### PR TITLE
Added config option to disable machines from engineer house not drop when breaked.

### PR DESCRIPTION
**Pull request by ReiDaTecnologia**
One thing I not like in AA is that you can not break the machines in the Engineer House because sometimes I want to move some machines but unfortunately I can't and unfortunately do not have an option to disable this in the mod config. For those as I, I've added an option to disable this. I hope you like my Addition!

### CODE REVIEW

**Comment by canitzp** [comment]
I don't think this is even a valid syntax: 
 
```
tile.stopFromDropping = If (ConfigBoolValues.ENGINEER_HOUSE_MACHINES_DROP.isEnabled());
```
and I also would provide a small method to check if its true, rather than reading from the config enum all the time

**Comment by ReiDaTecnologia** [comment]
Actually he already check if it's true or not, by default it's true and if the user want disable it he can change to false in the config file he will check and disable it.

**Comment by canitzp** [comment]
how did you change the files? I understand what you want to achieve, but your way is not possible, cause you're completly ignoring the necessary syntax

**Comment by ReiDaTecnologia** [comment]
The syntax that you talking about is "(ConfigBoolValues.ENGINEER_HOUSE_MACHINES_DROP.isEnabled())" , right? because this same syntax is already used by the mod, for exemple the "OreGen".

**Comment by Quarris** [comment]
The syntax is the use of the word `If`, a simple `ConfigBoolValues.ENGINEER_HOUSE_MACHINES_DROP.isEnabled()` is enough

**Comment by canitzp** [comment]
thx @Quarris
copy and paste is a bit shitty on mobile and so i lost the If in my change request

**Comment by canitzp** [comment]
```
boolean b = If(statement);
```
does not compile at all with java

**Comment by ReiDaTecnologia** [comment]
Changed.

**Comment by Ellpeck** [comment]
I don't think this would ba good change, I'm sorry.

**Pull request closed without merging**
