### PR TITLE
Update zh_CN file

### PR DESCRIPTION
**Pull request by TartaricAcid**
╰(￣▽￣)╭

### CODE REVIEW

**Comment by TartaricAcid** [comment]
Be probed by me.

**Comment by Ellpeck** [comment]
get a life!

**Comment by Ellpeck** [comment]
Isn't there still missing parts of the book translation? :P

**Comment by TartaricAcid** [comment]
All book translation is complete

**Comment by Ellpeck** [comment]
Huh, chinese people are weird.

**Pull request merged**
