### PR TITLE
r142: Fixes #1325, #1067. Remaps TehNut's Maven. Disabled A Tip using not UTF-8 Encoding

### LINKED ISSUE #1325: [Bug] 1.12.2, Localization Of Crystal Flux
Hey, the localization for Crystal Flux doesnt work is there any way we can fix that. If not do you give me permission to fork the mod and change the variables myself and publish to curse with 100% of points going to Ellpek

### PR DESCRIPTION
**Pull request by CrankySupertoon**

### CODE REVIEW

**Comment by CrankySupertoon** [comment]
Come on please

**Comment by MichaelHillcox** [comment]
Haha, that comment, i don’t like the string concat with an i18n, just makes translations useless for the prefix and suffix. Upon that, I’d need to talk to ellpeck about releasing another version for 1.12

**Comment by CrankySupertoon** [comment]
It’s either this or I’m going to mixin it in

**Comment by Ellpeck** [comment]
Yea, being a dick will really help get this pull request accepted.

**Pull request closed without merging**
