### PR TITLE
Redoing text for configs

### PR DESCRIPTION
**Pull request by Joshwoo70**
The text for some of the configs seems very off. so i decided to go through and fix it up.

### CODE REVIEW

**Comment by Ellpeck** [comment]
"lesser"? Isn't "less" right?

**Comment by Joshwoo70** [comment]
both seems alright...
edit : googled... seems less is a better choice.

**Comment by Joshwoo70** [comment]
updated should be much better now...

**Comment by Ellpeck** [comment]
See, I don't agree with you randomly changing default config values. I won't be merging this if you don't revert that. The advanced info isn't "For debugging", it's for everybody.

**Comment by Ellpeck** [comment]
To be perfectly honest, I don't understand this whole pull request. No one uses configs anyway, except people that are also smart enough to understand my shoddy grammar and explanations. So.. why the effort? Also, why the added, now even more apparent inconsistency?

**Comment by Joshwoo70** [comment]
1. I use configs they are awesome.
2. Inconsistencies? sure they will be.
3. The effort? i just find it easier to read and understand configs.
If you do not want to use these you may chose to close it.
4. I will revert the change. however some people find it very annoying when they press control key the actuallg additions thing pops up and obscures the view. a couple of modpacks has turned of the config for the very reason.

**Comment by Joshwoo70** [comment]
From the perspective of a player, a number of them find the infomation rather unintrestig as they all looks towards then like technical stuff. modpackers would have liked the feature so that they can edit recipes with ease. You wpild have ot think from the perspective of a player : "would i need it for regular gameplay?"

the statesment is not meant to critise you or such. just want to voice out my opinions. your mod is still awesome and i agree with it.

**Comment by Ellpeck** [comment]
No, I wasn't trying so say anything negative either. I think it's nice that you want to help, and true, your points are very valid. If people want to edit recipes though, you are going to have to use MineTweaker, as this is not a feature I'm going to want to implement any time soon :P

**Pull request merged**
