### PR TITLE
Update buildscript and resource data to 1.14.4

### PR DESCRIPTION
**Pull request by HyCraftHD**
This pull updates the buildscript files and basic resources to minecraft 1.14.4.

Don't know if that should be in the main branch or an extra 1.14.4 branch.

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
Targeting main is fine for 1.14, as 1.12 has been split off to a 1.12 branch.
Will review in a bit

**Comment by canitzp** [comment]
I already did this in my local branch, but i'm fine with this

**Comment by Shadows-of-Fire** [comment]
Theres a couple changes I'd make to this but they can wait for now.

**Comment by HyCraftHD** [comment]
Okay thanks.
@canitzp Which part do you try to port? So we don't do the same

**Comment by canitzp** [comment]
actually I don't have a clue and also not a lot of time. I just thought that nobody would do it, so I started in the ten minutes I had

**Pull request merged**
