### PR TITLE
Add config values for Leaf & Coal Generators. Closes #1277

### LINKED ISSUE #1277: Suggestion: Config to set leave eater generator rf per tick or delay for eating leaves.
Suggestion: Config to set leave eater generator rf per tick or delay for eating leaves.

This is more of a mod compat issue but I always wondered why people could adjust canola but not the coal and leave generators it’s hard to fit them in packs with other means of generators.

There is a mod called dynamic tree and when the leave eater eats a leave it respawn and he instantly eats it again and again and again this makes it the ultimate power generator. Would be nice if it was adjustable in case a Modpack adds dyn trees and actually additions!

or generaly a setting to adjust crystalflux to redstone flux conversion

### PR DESCRIPTION
**Pull request by iTitus**

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
@iTitus please retarget to the 1.12 branch

**Comment by iTitus** [comment]
will do ASAP

**Comment by iTitus** [comment]
It is done

**Comment by iTitus** [comment]
Good luck with the port ;)

**Pull request merged**
