### PR TITLE
Better Issue Management

### PR DESCRIPTION
**Pull request by tomodachi94**
As you likely know, managing issues is a tedious task. I am here today to bring you the convenience of issue templates.

Issue templates are just what they say they are. Templates for people to follow when creating issue templates.  This will help in an obvious way, to help people make complete issues.

But what about "question-issues"?

`config.yml` does that. It adds a button that links to the official documentation, to weed out question-issues.

Please offer up your critique and feedback!

### CODE REVIEW

**Comment by Tomodachi94** [comment]
I don't know why it isn't building. All I did was add a few files to `.github`...

**Comment by MichaelHillcox** [comment]
Main doesn't compile atm, it's all broken code. Also, I love the sales pitch haha

**Comment by Tomodachi94** [comment]
I just try to make it sound convincing. Don't believe me, check out the "Files Changed" tab to see for yourself! Also, a "code" review would be nice.

**Comment by Tomodachi94** [comment]
@Ellpeck I hate to do this normally, but could you look at this?

**Comment by MichaelHillcox** [comment]
I wouldn't recommend pinging Ell about this haha, I'm the maintainer of the project now, I'll view soon and let you know, bit busy atm.

**Comment by enderger** [comment]
Probably should add "resolves #1371"

**Comment by tomodachi94** [comment]
Screwed up my branches on my fork, so I did some Git wizardry to put it to another branch, but that closed the PR. I'll generate one momentarily...

**Pull request closed without merging**
